spring.application.name=api-gateway

server.port=8180

# Enable Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Enable API Gateway discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# User Microservice Route
spring.cloud.gateway.routes[0].id=user-microservice
spring.cloud.gateway.routes[0].uri=lb://user-microservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

# Product Microservice Route
spring.cloud.gateway.routes[1].id=product-microservice
spring.cloud.gateway.routes[1].uri=lb://product-microservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**

# Order Microservice Route
spring.cloud.gateway.routes[2].id=order-microservice
spring.cloud.gateway.routes[2].uri=lb://order-microservice
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**