spring.application.name=eureka-server
 
server.port = 8761
 
# disable this app - eureka client behaviour
eureka.client.register-with-eureka = false
eureka.client.fetch-registry = false
 
# set eureka dashboard hostname
eureka.instance.hostname = localhost